spring:
  application:
    name: dine-in-order-api
  datasource:
    url: ${MYSQL_URL}
    username:  ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
app:
  base-url: /api/v1
  cloudinary:
    cloud_name: ${CLOUD_NAME}
    api_key: ${API_KEY}
    api_secret: ${API_SECRET}

